### ISSUE TITLE
Source is missing Rakefile

### ISSUE THREAD

**Issue by tetherit** [AlexYaruki/sigar#1]
Hi there,

Your version has a few useful fixes compared to https://github.com/hyperic/sigar, however it seems the Rakefile was removed? - Any reason for that?

**Comment by AlexYaruki** [comment]
As I recall, Rakefile is build file for Ruby ? If yes, then I removed it to focus on languages I have experience and personally want to support. Also, I changed a little directory structure. If there is need to support for example Ruby, someone would need to do it through pull requests. I am open to cooperation.

**Comment by AlexYaruki** [comment]
Rakefile is present in bindings/ruby directory. Probably I moved it.
